module.exports = {
  baseRoute: require('./base'),
  registerRoute: require('./register'),
  userRoute: require('./user'),
  forgotPasswordRoute: require('./forgotPassword'),
  usersRoute: require('./users'),
  characteristicRoute: require('./characteristic'),
  dynamicFormRoute: require('./dynamicForm'),
  questionRoute: require('./question'),
  genericRoute: require('./genericData'),
  advancedSearchRoute: require('./advancedSearch'),
  serviceProviderRoute: require('./serviceProviders'),
  needRoute: require('./need'),
  needSatisfierRoute: require('./needSatisfier'),
  internalTypeRoute: require('./internalType'),
  serviceProvisionRoute: require('./serviceProvision'),
  programProvidereRoute: require('./programProviders'),
  programProvisionRoute: require('./programProvision'),
}
